data_dir: C:\Users\frigi\Desktop\NGC2784
object: ngc2784
work_dir: .
calib:
  superbias_path: calib/superbias.fits
  bias_combine: mean
  bias_sigma_clip: 0.0
runtime:
  n_jobs: 0
wavesol:
  profile_y: null
  y_half: 20
  xshift_max_abs: 6
  peak_snr: 5.0
  peak_prom_snr: 4.0
  peak_distance: 3
  gui_min_amp_sigma_k: 5.0
  neon_lines_csv: neon_lines.csv
  atlas_pdf: HeNeAr_atlas.pdf
frames:
  bias:
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840121.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840122.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840123.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840124.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840125.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840126.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840127.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840128.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840129.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840130.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840131.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840132.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840133.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840134.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840135.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840136.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840137.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840138.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840139.fts
  - C:\Users\frigi\Desktop\NGC2784\s238401\s23840140.fts
  flat:
  - C:\Users\frigi\Desktop\NGC2784\s238405\s23840510.fts
  - C:\Users\frigi\Desktop\NGC2784\s238405\s23840511.fts
  - C:\Users\frigi\Desktop\NGC2784\s238405\s23840512.fts
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841407.fts
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841408.fts
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841409.fts
  - C:\Users\frigi\Desktop\NGC2784\s238420\s23842006.fts
  - C:\Users\frigi\Desktop\NGC2784\s238420\s23842007.fts
  - C:\Users\frigi\Desktop\NGC2784\s238420\s23842008.fts
  - C:\Users\frigi\Desktop\NGC2784\s238420\s23842009.fts
  - C:\Users\frigi\Desktop\NGC2784\s238421\s23842110.fts
  - C:\Users\frigi\Desktop\NGC2784\s238421\s23842111.fts
  neon:
  - C:\Users\frigi\Desktop\NGC2784\s238405\s23840513.fts
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841406.fts
  - C:\Users\frigi\Desktop\NGC2784\s238420\s23842005.fts
  - C:\Users\frigi\Desktop\NGC2784\s238421\s23842109.fts
  sky: []
  obj:
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841404.fts
  - C:\Users\frigi\Desktop\NGC2784\s238414\s23841405.fts
  __setup__:
    mode: Spectra
    disperser: VPHG1200@540
    slit: '1.00'
    shape: 1040x4112
